### ISSUE TITLE
bug: auth-protected simple_crud with auth enabled allows open access to /objects/edit/:id

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#104]
If you set up a simple_crud like this:

````
 simple_crud(
        prefix => '/objects',
        auth => { view => { require_role => 'admin' }, edit => { require_role => 'admin' } },
        record_title => 'objects',
        db_table => 'objects',
       ...
};
````

Then DPSC will allow unauthorized access to /objects/edit/:id

**Comment by bigpresh** [comment]
That's... rather concerning.  I'll have a look as soon as I get a moment, if that's actually what's happening then that certainly wants fixing!  I'm pretty sure I remember it working correctly though - pretty sure there were already tests for it, and I remember testing it locally.  Hmm.

Also, sorry I somehow missed this when it was first raised!  I really need to sort out my GitHub notifications and some form of auto-nagging thing.
