### ISSUE TITLE
Interconnection between Simple Crud and Auth::RBAC

### ISSUE THREAD

**Issue by dancerbug** [bigpresh/Dancer-Plugin-SimpleCRUD#23]
Greetings, thanks for your work. I need to use this plugin Dancer::Plugin::SimpleCRUD with Dancer::Plugin::Auth::RBAC because only the admin users can modify the information. However, i didn't find any way to do this. Can you help me?

**Comment by bigpresh** [comment]
Closing this, as support for requiring logins / specific roles via D::P::Auth::Extensible was added some time ago.
