### ISSUE TITLE
Double prefix for load_app loaded and prefixed file

### ISSUE THREAD

**Issue by xvaara** [bigpresh/Dancer-Plugin-SimpleCRUD#36]
in the main app:
load_app 'app_admin';

on app_admin:

prefix '/admin';
simple_crud(....

causes double prefix with newer versions:

Trying to match 'GET /admin/foo' against /^\/admin\/admin\/foo$/ (generated from '/admin/admin/foo')

**Comment by joshrabinowitz** [comment]
@bigpresh is this still an issue?

**Comment by bigpresh** [comment]
Wow, er, this sat for quite some time.  Sorry!

Yes, I can confirm the behaviour, and also confirm that removing the use of `$args{dancer_prefix}` when constructing route paths to pass to `get`, `post` etc, and leaving it just to be used to formulate URLs for links in the templates, does indeed solve the problem.
