### ISSUE TITLE
Custom columns are not sortable

### ISSUE THREAD

**Issue by pjscott** [bigpresh/Dancer-Plugin-SimpleCRUD#44]
Sorry no time to write a patch, but just wanted to put this out there.

**Comment by joshrabinowitz** [comment]
I think this is outside the scope of DPSC, as it cannot use the database to sort these columns and it would mean sorting all the rows in a table just to show the first page.

**Comment by joshrabinowitz** [comment]
This is discussed in the code here: https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/blob/master/lib/Dancer/Plugin/SimpleCRUD.pm#L1228

**Comment by bigpresh** [comment]
Agree - we want to be able to let the DB handle sorting the data, as that's the DB's job.  Unfortunately, that means that data generated by our code can't be sorted, unless we stop getting the DB to do sorting and pagination and instead fetch the entire (potentially huge) resultset into memory and sort it there.

I consider this "fixed" in that there's no longer ineffectual sort links offered for custom columns, so closing this.
