### ISSUE TITLE
'next page' after searches gives uninitialized value error

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#47]
Steps to reproduce:

* Setup D:P:SC on a table with M rows and enable sorting and pagination for N rows, where N<M.

* Perform a search returning more than N rows, and attempt to follow the 'next page' link to the second page

Expected Behavior: 
* Next page shown

Observed Behavior: 
* Error: "Warning caught during route execution: Use of uninitialized value in string eq at .../Dancer/Plugin/SimpleCRUD.pm line 968.

Working up a patch now

**Comment by bigpresh** [comment]
Fixed by your PR-48 - thanks for the report and especially the fix! :)
