### ISSUE TITLE
New where_filter stuff doesn't go far enough

### ISSUE THREAD

**Issue by bigpresh** [bigpresh/Dancer-Plugin-SimpleCRUD#60]
The current where_filter stuff is handy - but it's only used when listing records.

I think if it's there, it needs to also apply to fetching/updating/deleting records everywhere.

Otherwise, for example, if you had, for example,  `where_filter => { category => 'public' }` set, then only records in the "public" category would be listed or found in searches.  However, if you click on one, then change the ID in the URL, you can easily retrieve/edit/delete other ones, too.

As i see it, if you're using that option, it's to enforce only a subset of records being operated on, so that should be the case everywhere.

As an aside, I'm implementing support for `where_filter` being a coderef that's called at route execution time, in order to be able to, for e.g. limit the records based on the logged-in user's permissions- for instance:

```perl
...
where_filter => sub { return { company_id => logged_in_user()->{company_id} } },
...
```
I think that will make this feature much more useful, but until it works securely it's not that useful yet :)

@joshrabinowitz - a mention just so you'll see this, interested in your thoughts.

**Comment by joshrabinowitz** [comment]
@bigpresh: Total agreement about the first four sentences.

Re: implementation, that sounds good also.

**Comment by joshrabinowitz** [comment]
I think we can close this

**Comment by bigpresh** [comment]
Agreed, closing.
