### ISSUE TITLE
custom_column definitions change display order

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#65]
If you define multiple custom_columns for a table, the order they appear in table displays seems random.

**Comment by bigpresh** [comment]
Hmm, yes.  They're defined as a hashref, so yeah, the ordering is essentially random.

Perhaps providing `custom_columns` as a hashref should be deprecated, in favour of an arrayref of hashrefs, which could be processed in order.

**Comment by bigpresh** [comment]
Done - custom_columns is now an arrayref, so the order can be controlled (but a hashref is still supported for backwards compat)
