### ISSUE TITLE
customizing content in data cells

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#70]
I'm not sure if this is a documentation request or a feature request.

Is there a way to customize the display of content in cells? 

I could imagine specifying a subref to be called for cell content display that would receive ($cell_data, $row_data) like transform() does.  Is anything like this currently possible?

**Comment by bigpresh** [comment]
Something like transform, but called for each and every cell, you mean?

I'd imagine most presentational stuff could be done with CSS, surely?

**Comment by joshrabinowitz** [comment]
No, not presentational, content-wise. 

For example, I'd like to add an <a href="linkhere">original content</a> to a cell, or assemble data from multiple columns into one cell without using custom_columns.

**Comment by joshrabinowitz** [comment]
wouldnt necessarily have to be for every cell. Perhaps I could specify just certain columns that would allow custom content. I'll try to work up a usage example later today.

**Comment by bigpresh** [comment]
Hmm.   The example app does just that via custom_columns, but that's adding a new column, not modifying an existing one.

I can see what you mean, a direct way to pass through callbacks to HTML::Table::FromDatabase to act upon individual cells, as opposed to creating new ones, could be handy.

It could, perhaps, be as simple as allowing the specification of an entry in `custom_columns` whose name matches that of a column that exists in the table to over-ride it, maybe?

**Comment by joshrabinowitz** [comment]
I think that solution would be pretty elegant and consistent with the existing interface. I like it.

**Comment by joshrabinowitz** [comment]
I just discovered that it _does_ work this way, except that if you use custom_columns' transform function to override the display of a sortable column, it becomes unsortable. 

This is different than #44 because this column would be otherwise sortable.

I can see cases where you would and wouldn't want to leave a previous sortable column sortable after applying a custom_column transformation, though I think in general it'd be preferable to leave it sortable.

**Comment by joshrabinowitz** [comment]
Actually I just did more testing and it doesn't just override the normal callback, it also duplicates that column. That is, if I have a table like
````
 create table widgets ( id int, name varchar, desc varchar);
````
and I say
```
 simple_crud(
    prefix="/widgets",
   db_table=>"widgets",
   custom_columns=>[ 
      {name=>'name', raw_column=>'name', transform=>sub { "hi $_[0]" } },
  ]
 );
````
Then I'll see the 'name' column twice (with the transform applied each time) in the resulting HTML. 

I'll see if this is easily fixable. Also haven't tested with the deprecated hashref-based version of custom_columns.

**Comment by joshrabinowitz** [comment]
For reference, there is more discussion about this topic at #78

**Comment by joshrabinowitz** [comment]
This feature has been added. Issue closed.
