### ISSUE TITLE
simplecrud interfaces don't allow addable without editabilty, and vice versa

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#81]
Currently you can allow permission to delete rows, and to add/edit rows. 

But you cannot make a simplecrud interface to a table addable but not editable, or vice-versa

**Comment by bigpresh** [comment]
I'm not sure how common a requirement this would be, but I imagine you're raising it because you need it, and you've implemented it, so all good :)

**Comment by bigpresh** [comment]
Done in #82
