### ISSUE TITLE
crud interfaces don't allow deletability without editabilty

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-SimpleCRUD#83]
It's not possible to setup a simplecrud interface that allows rows to be deleted but not added

**Comment by joshrabinowitz** [comment]
@bigpresh do you want to close bugs as the corresponding changes are merged, or when they're released?

**Comment by bigpresh** [comment]
I tend to just close them once the work involved hits master, usually, to keep the list of open issues shorter.

I wouldn't object to leaving them open, tagged "fixed in next release" or similar, though.

**Comment by joshrabinowitz** [comment]
Yeah I agree on closing them when the work hits master. Closing this.
